#!/usr/bin/env node
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),fixture=spawnSync(process.execPath,[path.join(root,"tests/v011-collaboration-contracts.mjs")],{encoding:"utf8",maxBuffer:20_000_000});assert.equal(fixture.status,0,fixture.stderr||fixture.stdout);const info=JSON.parse(fixture.stdout.trim().split("\n").at(-1));assert.ok(fs.existsSync(info.productPreview));
async function loadPlaywright(){if(process.env.MINT_PLAYWRIGHT_MODULE)return import(process.env.MINT_PLAYWRIGHT_MODULE.startsWith("/")?pathToFileURL(process.env.MINT_PLAYWRIGHT_MODULE).href:process.env.MINT_PLAYWRIGHT_MODULE);const modules=process.env.RUNTIME_NODE_MODULES;if(!modules)return import("playwright");const require=createRequire(path.join(modules,"package.json"));return import(pathToFileURL(require.resolve("playwright")).href)}
const playwright=await loadPlaywright(),chromium=playwright.chromium||playwright.default?.chromium;assert.ok(chromium);const browser=await chromium.launch({headless:true,executablePath:process.env.MINT_CHROMIUM_EXECUTABLE||undefined});
try{
  const relocatedDir=fs.mkdtempSync(path.join(os.tmpdir(),'mint-relocated-')),relocated=path.join(relocatedDir,'renamed-offline-section.html');fs.copyFileSync(info.productPreview,relocated);const page=await browser.newPage({viewport:{width:1920,height:1080}}),errors=[];page.on("pageerror",error=>errors.push(error.message));await page.goto(pathToFileURL(relocated).href);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('[data-edit-kind="media"] img').count(),1);
  assert.equal(await page.locator('[data-save-workfile]').isVisible(),true);assert.equal(await page.locator('[data-export-package]').isVisible(),false);await page.keyboard.press('e');
  const title=page.locator('[data-scene-id="MC-one"] [data-title-contract]');await title.fill('产品结论已更新');await title.blur();await page.evaluate(()=>window.mintFields.flush());
  const chart=page.locator('[data-scene-id="MC-one"] [data-edit-kind="chart"]');await chart.click();await page.locator('.mint-editor [name="title"]').fill('更新后的比较');await page.locator('.mint-editor textarea').fill('系列/分类\t肯尼亚\t坦桑尼亚\n数值\t3\t5');await page.locator('.mint-editor [data-apply]').click();
  const media=page.locator('[data-scene-id="MC-one"] [data-edit-kind="media"]');await media.click();await page.locator('.mint-editor [name="alt"]').fill('更新图片');await page.locator('.mint-editor [name="file"]').setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64')});await page.locator('.mint-editor [data-apply]').click();
  await page.evaluate(()=>{window.showSaveFilePicker=async()=>({name:'product-current.mint-section.html',createWritable:async()=>({write:async blob=>{window.__mintSavedHtml=await blob.text()},close:async()=>{}})})});await page.locator('[data-save-workfile]').click();await page.waitForFunction(()=>typeof window.__mintSavedHtml==='string');
  const editedSection=path.join(os.tmpdir(),'product-edited.mint-section.html');fs.writeFileSync(editedSection,await page.evaluate(()=>window.__mintSavedHtml));
  const fallbackDownload=page.waitForEvent('download');const fallbackMode=await page.evaluate(()=>{delete window.showSaveFilePicker;return window.mintPackageExport.saveWorkfile()});const fallback=await fallbackDownload;const fallbackFile=path.join(os.tmpdir(),'product-fallback.mint-section.html');await fallback.saveAs(fallbackFile);assert.equal(fallbackMode.mode,'download');assert.match(fs.readFileSync(fallbackFile,'utf8'),/id="mint-package-data"/);
  const mergedEdited=path.join(info.temp,'merged-edited'),merge=spawnSync(process.execPath,[path.join(root,'scripts/collaboration-package.mjs'),'merge',info.brief,mergedEdited,editedSection,info.financeWork],{encoding:'utf8',maxBuffer:20_000_000});assert.equal(merge.status,0,merge.stderr||merge.stdout);let model=JSON.parse(fs.readFileSync(path.join(mergedEdited,'report-model.json'),'utf8'));assert.equal(model.sceneById['section-product__MC-one'].displayTitle,'产品结论已更新');assert.equal(model.charts['section-product__C1'].title,'更新后的比较');assert.deepEqual(model.charts['section-product__C1'].series[0].values,[3,5]);assert.equal(model.media['section-product__M1'].alt,'更新图片');assert.match(model.media['section-product__M1'].dataUrl,/^data:image\/png;base64,/);
  await page.goto(pathToFileURL(path.join(mergedEdited,'weekly-review-review.mint-report.html')).href);await page.keyboard.press('e');const table=page.locator('[data-scene-id="section-finance__MC-one"] [data-edit-kind="table"]');await table.scrollIntoViewIfNeeded();await table.click();await page.locator('.mint-editor textarea').fill('国家\t数值\n肯尼亚\t10\n坦桑尼亚\t12');await page.locator('.mint-editor [data-apply]').click();const diagram=page.locator('[data-scene-id="section-finance__MC-one"] [data-edit-kind="diagram"]');await diagram.click();await page.locator('.mint-editor textarea').fill('{"nodes":[{"id":"n1","label":"新起点"}],"edges":[]}');await page.locator('.mint-editor [data-apply]').click();
  await page.evaluate(()=>{window.showSaveFilePicker=async()=>({name:'weekly-review-current.mint-report.html',createWritable:async()=>({write:async blob=>{window.__mintSavedReport=await blob.text()},close:async()=>{}})})});await page.locator('[data-save-workfile]').click();await page.waitForFunction(()=>typeof window.__mintSavedReport==='string');const target=path.join(os.tmpdir(),'weekly-review-edited.mint-report.html');fs.writeFileSync(target,await page.evaluate(()=>window.__mintSavedReport));
  const unpacked=path.join(os.tmpdir(),`mint-unpacked-${Date.now()}`),unpack=spawnSync(process.execPath,[path.join(root,'scripts/collaboration-package.mjs'),'unpack',target,unpacked],{encoding:'utf8',maxBuffer:20_000_000});assert.equal(unpack.status,0,unpack.stderr||unpack.stdout);model=JSON.parse(fs.readFileSync(path.join(unpacked,'report-model.json'),'utf8'));assert.deepEqual(model.tables['section-finance__T1'].rows,[['肯尼亚','10'],['坦桑尼亚','12']]);assert.equal(model.diagrams['section-finance__D1'].nodes[0].label,'新起点');assert.ok(model.userEdits.length>=5);const publish=spawnSync(process.execPath,[path.join(root,'scripts/run-creative-workflow.mjs'),'publish',unpacked],{encoding:'utf8',maxBuffer:80_000_000,env:process.env});assert.equal(publish.status,0,publish.stderr||publish.stdout);const pptLayout=JSON.parse(fs.readFileSync(path.join(unpacked,'ppt-layout.json'),'utf8')),publishedTable=pptLayout.scenes.flatMap(scene=>scene.objects).find(object=>object.fieldPath==='tables.section-finance__T1'),publishedDiagram=pptLayout.scenes.flatMap(scene=>scene.objects).find(object=>object.fieldPath==='diagrams.section-finance__D1');assert.deepEqual(publishedTable.value.rows,[['肯尼亚','10'],['坦桑尼亚','12']]);assert.equal(publishedDiagram.value.nodes[0].label,'新起点');assert.equal(JSON.parse(fs.readFileSync(path.join(unpacked,'delivery-manifest.json'),'utf8')).checks.pdfCurrent,true);assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,sectionEditMerged:true,textEditable:true,tableEditable:true,chartEditable:true,mediaEditable:true,diagramEditable:true,workfilePersistsEdits:true,directSave:true,fallbackDownload:true,offlineRelocated:true,editedMergedWorkfilePublished:true,workfile:target}));
}finally{await browser.close()}
