#!/usr/bin/env node
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath, pathToFileURL } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),fixture=spawnSync(process.execPath,[path.join(root,"tests/v011-collaboration-contracts.mjs")],{encoding:"utf8",maxBuffer:30_000_000});assert.equal(fixture.status,0,fixture.stderr||fixture.stdout);const info=JSON.parse(fixture.stdout.trim().split("\n").at(-1));
const html=fs.readFileSync(info.productWork,"utf8"),match=html.match(/<script\b[^>]*id=["']mint-package-data["'][^>]*>([\s\S]*?)<\/script>/i);assert.ok(match);const payload=JSON.parse(match[1]),large=Buffer.alloc(60*1024*1024,0x6d),hash=crypto.createHash("sha256").update(large).digest("hex"),manifestEntry=payload.entries.find(entry=>entry.name==="mint-package.json"),manifest=JSON.parse(Buffer.from(manifestEntry.base64,"base64").toString("utf8"));manifest.files["assets/large.bin"]=hash;manifest.immutableFiles=[...new Set([...(manifest.immutableFiles||[]),"assets/large.bin"])];manifestEntry.base64=Buffer.from(`${JSON.stringify(manifest,null,2)}\n`).toString("base64");payload.entries.push({name:"assets/large.bin",base64:large.toString("base64")});const largeFile=path.join(os.tmpdir(),`mint-large-${Date.now()}.mint-section.html`);fs.writeFileSync(largeFile,html.replace(match[1],JSON.stringify(payload).replaceAll("<","\\u003c")));
const {chromium}=await import(process.env.MINT_PLAYWRIGHT_MODULE||"playwright"),browser=await chromium.launch({headless:true,executablePath:process.env.MINT_CHROMIUM_EXECUTABLE||undefined});
try{const page=await browser.newPage({viewport:{width:1920,height:1080}}),started=Date.now();await page.goto(pathToFileURL(largeFile).href,{waitUntil:"load",timeout:120000});await page.evaluate(()=>document.fonts.ready);const openMs=Date.now()-started;await page.keyboard.press("e");const title=page.locator("[data-title-contract]").first();await title.fill("大文件仍可编辑");await title.blur();await page.evaluate(()=>window.mintFields.flush());await page.evaluate(()=>{window.showSaveFilePicker=async()=>({name:"large.html",createWritable:async()=>({write:async blob=>{window.__savedLargeBytes=blob.size},close:async()=>{}})})});const saveStarted=Date.now(),result=await page.evaluate(()=>window.mintPackageExport.saveWorkfile());const saveMs=Date.now()-saveStarted,savedBytes=await page.evaluate(()=>window.__savedLargeBytes);assert.equal(result.mode,"direct");assert.ok(savedBytes>80*1024*1024);assert.equal(await title.textContent(),"大文件仍可编辑");const unpacked=path.join(os.tmpdir(),`mint-large-unpacked-${Date.now()}`),unpack=spawnSync(process.execPath,[path.join(root,"scripts/collaboration-package.mjs"),"unpack",largeFile,unpacked],{encoding:"utf8",maxBuffer:30_000_000});assert.equal(unpack.status,0,unpack.stderr||unpack.stdout);assert.equal(fs.statSync(path.join(unpacked,"assets/large.bin")).size,large.length);console.log(JSON.stringify({passed:true,assetMB:60,workfileMB:Number((fs.statSync(largeFile).size/1024/1024).toFixed(1)),openMs,saveMs,editable:true,unpackable:true}));}finally{await browser.close()}
